export {
    getData,
    postData,
    FETCH_FRIENDS_DATA_START,
    FETCH_FRIENDS_DATA_SUCCESS,
    FETCH_FRIENDS_DATA_FAILURE,
    NEW_FRIENDS_ADDED,
    NEW_FRIENDS_ADDED_SUCCESS,
    NEW_FRIENDS_ADDED_FAILURE
} from './friendsAction'